# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.64.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finapi
from finapi.api.payments_api import PaymentsApi  # noqa: E501
from finapi.rest import ApiException


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = finapi.api.payments_api.PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_payments(self):
        """Test case for get_payments

        Get payments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
