# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.64.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finapi
from finapi.models.error_message import ErrorMessage  # noqa: E501
from finapi.rest import ApiException


class TestErrorMessage(unittest.TestCase):
    """ErrorMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorMessage(self):
        """Test ErrorMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = finapi.models.error_message.ErrorMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
