# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.64.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finapi
from finapi.models.bank_connection import BankConnection  # noqa: E501
from finapi.rest import ApiException


class TestBankConnection(unittest.TestCase):
    """BankConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankConnection(self):
        """Test BankConnection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = finapi.models.bank_connection.BankConnection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
