# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.64.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finapi
from finapi.api.securities_api import SecuritiesApi  # noqa: E501
from finapi.rest import ApiException


class TestSecuritiesApi(unittest.TestCase):
    """SecuritiesApi unit test stubs"""

    def setUp(self):
        self.api = finapi.api.securities_api.SecuritiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_and_search_all_securities(self):
        """Test case for get_and_search_all_securities

        Get and search all securities  # noqa: E501
        """
        pass

    def test_get_multiple_securities(self):
        """Test case for get_multiple_securities

        Get multiple securities  # noqa: E501
        """
        pass

    def test_get_security(self):
        """Test case for get_security

        Get a security  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
