# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.64.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finapi
from finapi.models.check_categorization_transaction_data import CheckCategorizationTransactionData  # noqa: E501
from finapi.rest import ApiException


class TestCheckCategorizationTransactionData(unittest.TestCase):
    """CheckCategorizationTransactionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckCategorizationTransactionData(self):
        """Test CheckCategorizationTransactionData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = finapi.models.check_categorization_transaction_data.CheckCategorizationTransactionData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
