# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.64.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finapi
from finapi.models.single_money_transfer_recipient_data import SingleMoneyTransferRecipientData  # noqa: E501
from finapi.rest import ApiException


class TestSingleMoneyTransferRecipientData(unittest.TestCase):
    """SingleMoneyTransferRecipientData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleMoneyTransferRecipientData(self):
        """Test SingleMoneyTransferRecipientData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = finapi.models.single_money_transfer_recipient_data.SingleMoneyTransferRecipientData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
