# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.64.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finapi
from finapi.models.iban_rule_params import IbanRuleParams  # noqa: E501
from finapi.rest import ApiException


class TestIbanRuleParams(unittest.TestCase):
    """IbanRuleParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIbanRuleParams(self):
        """Test IbanRuleParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = finapi.models.iban_rule_params.IbanRuleParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
